### ISSUE TITLE
Errors when doing npm start

### ISSUE THREAD

**Issue by TheAwesomeGem** [naviapps/create-nw-react-app#2]
Here's the issue: https://i.gyazo.com/5302ac976520365b7be617a4c5deb644.png

**Comment by naviapis** [comment]
It worked in my environment.
* Windows 7, node v6.10.2, npm 5.5.1
* macOS 10.13.1, node v6.10.3, npm 5.5.1

Approach 1
Are you using proxy settings?
・https://github.com/Microsoft/vscode/issues/2384
・https://github.com/Microsoft/vscode/issues/28621

Approach 2
Please delete the /cache folder and retry.

Approach 3
Update the problem package to the latest version. (installed: v2.4.1)
```sh
npm install yauzl@2.9.1
```

Thanks.

**Comment by TheAwesomeGem** [comment]
Thank you. Will try that when I get a chance!

**Comment by jasonbronson** [comment]
I'm having this issue now and I'm behind a corporate firewall.
Although dev tools states it returns a 200 request to the following plugin url
https://liximomo.gallerycdn.vsassets.io/extensions/liximomo/sftp/0.8.10/1511144665016/Microsoft.VisualStudio.Services.Content.Details
I then get the error message as well.

`end of central directory record signature not found: Error: end of central directory record signature not found,    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:183:14,    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:618:5,    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\fd-slicer\index.js:32:7,    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
i.onError @ extensionEditor.ts:894
(anonymous) @ event.ts:410
(anonymous) @ event.ts:406
(anonymous) @ event.ts:222
i @ eventEmitter.ts:295
e._emitToSpecificTypeListeners @ eventEmitter.ts:162
e._emitEvents @ eventEmitter.ts:181
(anonymous) @ eventEmitter.ts:129
i @ eventEmitter.ts:295
e._emitToBulkListeners @ eventEmitter.ts:170
e._emitEvents @ eventEmitter.ts:176
e.emit @ eventEmitter.ts:196
(anonymous) @ actions.ts:237
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.doRequest.n.TPromise.t.handlers.(anonymous function) @ ipc.ts:254
e.onMessage @ ipc.ts:319
(anonymous) @ ipc.ts:206
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560`

Adding user/pass to the corp firewall proxy url doesn't help it.

`"http.proxy": "http://192.1.1.1:80",
    "http.proxyStrictSSL": false,
    `

```
Tried to run basic npm command itself to verify if 
 /c/Program Files/Microsoft VS Code/resources/app
$ npm update
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t ssh://git@github.com/bpasero/chokidar.git
npm ERR!
npm ERR! ssh: connect to host github.com port 22: Connection timed out
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

```

It was working and I could install extensions before. I'm able to update fine in VS code to latest version using proxy settings.

![capture](https://user-images.githubusercontent.com/1443624/33037630-09fd04e2-cde7-11e7-9c4a-f6617a86fdc9.PNG)
