### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by jlmodell** [naviapps/create-nw-react-app#35]
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at noopServiceWorkerMiddleware (C:\projects\nwjs\sa_client\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\projects\nwjs\sa_client\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:317:13)
    at C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:335:12)
    at next (C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\projects\nwjs\sa_client\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\projects\nwjs\sa_client\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:317:13)
    at C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:335:12)
    at next (C:\projects\nwjs\sa_client\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\projects\nwjs\sa_client\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\projects\nwjs\sa_client\node_modules\express\lib\router\layer.js:95:5)`

When I google this error, the solution seems to be to update react-scripts to 3.4.0 but I can't do that  while working with a create-nw-react-app bootstrap project.

Is there something I can do to update nw-react-scripts to 3.4.0?  I started looking at the code to see what is different but not sure what i'm looking for.

**Comment by ericmilaneze** [comment]
I'm having the same issue. Did you get any help with that?

**Comment by talentlessguy** [comment]
Same... when using `pnpm`

**Comment by ldevalbray** [comment]
Hello, any updates on this ?

**Comment by naviapis** [comment]
v3.4.1 released.

pacakge.json

```diff
 {
   "dependencies": {
-    "nw-react-scripts": "3.3.0"
+    "nw-react-scripts": "3.4.1"
   }
 }
```

and `yarn` or `npm update`

If you still have problems, please let us know.
