### ISSUE TITLE
Certificate has expired?

### ISSUE THREAD

**Issue by tolokoban** [naviapps/create-nw-react-app#40]
Recently (August 22, 2020 for example), I often experience a certificate error on `npm start`:

```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'CERT_HAS_EXPIRED'
}
```

The code executed by `npm start` is this:
```
REACT_APP_WEBSOINS=DEV nw-react-scripts start
```
`npm update` seemed to fixed the problem, but it as occurred again and now there is nothing more to update.

Do you know of what certificate this is all about?

**Comment by blakewood84** [comment]
Getting the same error here! Looking for a solution

**Comment by blakewood84** [comment]
I'm getting this with other NW.js boilerplates

**Comment by Naveenchandra07** [comment]
Hello, do we have any resolution for this issue?
